package com.sweak.unlockmaster.domain

const val DEFAULT_UNLOCK_LIMIT = 40

const val DEFAULT_MOBILIZING_NOTIFICATIONS_FREQUENCY_PERCENTAGE = 25
val AVAILABLE_MOBILIZING_NOTIFICATIONS_FREQUENCY_PERCENTAGES = listOf(10, 25, 50)