package com.sweak.unlockmaster.domain

const val DEFAULT_UNLOCK_LIMIT = 40
const val UNLOCK_LIMIT_LOWER_BOUND = 10
const val UNLOCK_LIMIT_UPPER_BOUND = 70

const val DEFAULT_MOBILIZING_NOTIFICATIONS_FREQUENCY_PERCENTAGE = 25
val AVAILABLE_MOBILIZING_NOTIFICATIONS_FREQUENCY_PERCENTAGES = listOf(10, 25, 50)

const val DEFAULT_DAILY_WRAP_UPS_NOTIFICATIONS_TIME_IN_MINUTES_PAST_MIDNIGHT = 1260 // 21:00
const val MINIMAL_DAILY_WRAP_UPS_NOTIFICATIONS_TIME_HOUR_OF_DAY = 20 // 20:00 - 23:59 is allowed